# Generated by Django 5.0.5 on 2024-06-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('funder', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('duration_in_months', models.PositiveIntegerField()),
                ('years_since_phd_start', models.PositiveIntegerField()),
                ('years_since_phd_end', models.PositiveIntegerField()),
                ('link', models.URLField()),
                ('fund_type', models.CharField(choices=[('fellowship', 'Fellowship'), ('grant', 'Grant')], max_length=10)),
            ],
        ),
    ]
