# Generated by Django 5.0.5 on 2024-06-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='years_since_phd_end',
            new_name='max_years_since_phd',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='years_since_phd_start',
            new_name='min_years_since_phd',
        ),
    ]
