# Generated by Django 5.0.5 on 2024-06-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_rename_years_since_phd_end_fund_max_years_since_phd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='max_fund_amount',
            field=models.CharField(default='1000e', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='duration_in_months',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fund',
            name='max_years_since_phd',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='min_years_since_phd',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
