# Generated by Django 5.0.5 on 2024-06-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_fund_max_fund_amount_alter_fund_duration_in_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_type',
        ),
    ]
