# Generated by Django 5.0.5 on 2024-06-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_remove_fund_fund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='eligibility_text',
            field=models.TextField(blank=True),
        ),
    ]
