# Generated by Django 5.0.5 on 2024-06-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_fund_eligibility_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='duration_in_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='eligibility_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='funder',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='fund',
            name='link',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='fund',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='max_fund_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='max_years_since_phd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='min_years_since_phd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='fund',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
