# Generated by Django 5.0.5 on 2024-07-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_alter_fund_duration_in_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='location_found',
            field=models.BooleanField(default=False),
        ),
    ]
